.TH ldb 1 "$Date: 2014/05/15 21:25:34 $" 
.SH NAME
ldb \- explore and manage leveldb instances
.SH SYNOPSYS
.nf
\fBldb\fP [\fIpath\fP] [\fIoptions\fP] \fP
.PP
\fBldb\fP [\fIpath\fP] \fP
.fi
.SH DESCRIPTION
The repl is invoked when only a path and optionally -c is specified.
.SH "RETURN VALUE"
0 for successful completion, 1 for environmental problems (file not
found, invalid options, IO error, etc), 2 for a corrupt file and 3 for
an internal error or unhandled situation.
.SH "SEE ALSO"
.BR leveldb"(3)"
.SH "AUTHOR"
Paolo Fragomeni <paolo@async.ly>
Lars Magnus Skog <ralphtheninja@riseup.net>
Joseph Werle <joseph@werle.io>
.PP
Distribued with the MIT license.

